create table "public"."clients" (
  "id"         bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "name"       text not null,
  "user_id"    uuid not null,
  "email"      text not null,
  "city"       text not null,
  "country"    text not null,
  "state"      text not null,
  "postcode"   text not null,
  "address"    text not null,
  "deleted"    boolean not null default false
);

alter table "public"."clients" enable row level security;

create table "public"."companies" (
  "id"             bigint generated by default as identity not null,
  "created_at"     timestamp with time zone not null default now(),
  "name"           text not null,
  "email"          text not null,
  "city"           text not null,
  "state"          text not null,
  "postcode"       text not null,
  "country"        text not null,
  "bsb"            text not null,
  "account_number" text not null,
  "address"        text not null,
  "user_id"        uuid,
  "deleted"        boolean not null default false
);

alter table "public"."companies" enable row level security;

create table "public"."invoices" (
  "id"         text not null,
  "lines"      jsonb[] not null,
  "company_id" bigint not null,
  "client_id"  bigint not null,
  "user_id"    uuid not null,
  "notes"      text not null,
  "date"       date not null,
  "created_at" timestamp with time zone not null default now(),
  "deleted"    boolean not null default false,
  "status"     public."InvoiceStatus" not null default 'unpaid'::"public"."InvoiceStatus"
);

alter table "public"."invoices" enable row level security;

-- Primary keys
create unique index clients_pkey  on public.clients  using btree (id);
create unique index companies_pkey on public.companies using btree (id);
create unique index invoices_pkey  on public.invoices  using btree (id);

alter table "public"."clients"   add constraint "clients_pkey"   primary key using index "clients_pkey";
alter table "public"."companies" add constraint "companies_pkey" primary key using index "companies_pkey";
alter table "public"."invoices"  add constraint "invoices_pkey"  primary key using index "invoices_pkey";

-- Foreign keys
alter table "public"."clients"
  add constraint "clients_user_id_fkey"
  foreign key (user_id) references auth.users(id) not valid;
alter table "public"."clients" validate constraint "clients_user_id_fkey";

alter table "public"."companies"
  add constraint "companies_user_id_fkey"
  foreign key (user_id) references auth.users(id) not valid;
alter table "public"."companies" validate constraint "companies_user_id_fkey";

alter table "public"."invoices"
  add constraint "invoices_client_id_fkey"
  foreign key (client_id) references public.clients(id) not valid;
alter table "public"."invoices" validate constraint "invoices_client_id_fkey";

alter table "public"."invoices"
  add constraint "invoices_company_id_fkey"
  foreign key (company_id) references public.companies(id) not valid;
alter table "public"."invoices" validate constraint "invoices_company_id_fkey";

alter table "public"."invoices"
  add constraint "invoices_user_id_fkey"
  foreign key (user_id) references auth.users(id) not valid;
alter table "public"."invoices" validate constraint "invoices_user_id_fkey";
